// <auto-generated />
namespace GLMainProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddFacture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFacture));
        
        string IMigrationMetadata.Id
        {
            get { return "202205110444450_AddFacture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
